// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/news": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-news"
                ],
                "summary": "List news (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Статус: draft|published|archived",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Фильтр по категории",
                        "name": "category_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Фильтр по типу медиа",
                        "name": "media_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Поиск по заголовку/анонсу",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Номер страницы",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Размер страницы (по умолчанию 20)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Не удалось получить список новостей",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-news"
                ],
                "summary": "Create news (admin)",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateNewsRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.News"
                        }
                    },
                    "400": {
                        "description": "Некорректный JSON или ошибка валидации",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    }
                }
            }
        },
        "/admin/news/categories": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "news-categories"
                ],
                "summary": "Получить список категорий новостей",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.NewsCategory"
                            }
                        }
                    },
                    "500": {
                        "description": "Не удалось получить категории",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "news-categories"
                ],
                "summary": "Создать категорию новостей",
                "parameters": [
                    {
                        "description": "Данные категории",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateNewsCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.NewsCategory"
                        }
                    },
                    "400": {
                        "description": "Некорректное тело запроса или ошибка валидации",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    },
                    "500": {
                        "description": "Не удалось создать категорию",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    }
                }
            }
        },
        "/admin/news/categories/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "news-categories"
                ],
                "summary": "Получить категорию по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID категории",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.NewsCategory"
                        }
                    },
                    "404": {
                        "description": "Категория не найдена",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    },
                    "500": {
                        "description": "Ошибка при получении категории",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "news-categories"
                ],
                "summary": "Обновить категорию новостей",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID категории",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateNewsCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.NewsCategory"
                        }
                    },
                    "400": {
                        "description": "Некорректное тело запроса или ошибка валидации",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    },
                    "404": {
                        "description": "Категория не найдена",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    },
                    "500": {
                        "description": "Не удалось обновить категорию",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "news-categories"
                ],
                "summary": "Удалить категорию новостей",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID категории",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Категория успешно удалена"
                    },
                    "404": {
                        "description": "Категория не найдена",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    },
                    "500": {
                        "description": "Не удалось удалить категорию",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    }
                }
            }
        },
        "/admin/news/{id}": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-news"
                ],
                "summary": "Update news (admin)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateNewsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.News"
                        }
                    },
                    "400": {
                        "description": "Некорректный JSON или ошибка валидации",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    },
                    "404": {
                        "description": "Новость не найдена",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "tags": [
                    "admin-news"
                ],
                "summary": "Delete news (admin)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Новость не найдена",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    }
                }
            }
        },
        "/admin/stats": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Admin statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Stats"
                        }
                    }
                }
            }
        },
        "/admin/trips": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Создание нового тура (только админ)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trips"
                ],
                "summary": "Create trip (admin)",
                "parameters": [
                    {
                        "description": "Trip data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateTripRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Trip"
                        }
                    },
                    "400": {
                        "description": "Некорректные данные",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    },
                    "500": {
                        "description": "Ошибка при создании тура",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    }
                }
            }
        },
        "/admin/trips/{id}": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Обновление данных тура (только админ)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trips"
                ],
                "summary": "Update trip (admin)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Trip ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Trip update",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateTripRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Trip"
                        }
                    },
                    "400": {
                        "description": "Некорректные данные",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    },
                    "404": {
                        "description": "Тур не найден",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    },
                    "500": {
                        "description": "Ошибка при обновлении тура",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Удаление тура (только админ)",
                "tags": [
                    "trips"
                ],
                "summary": "Delete trip (admin)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Trip ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Тур не найден",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    },
                    "500": {
                        "description": "Ошибка при удалении тура",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    }
                }
            }
        },
        "/admin/users": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Получить всех пользователей",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.User"
                            }
                        }
                    },
                    "500": {
                        "description": "Не удалось получить список пользователей",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Создать пользователя",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "400": {
                        "description": "Некорректное тело запроса",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    },
                    "500": {
                        "description": "Ошибка при создании пользователя",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    }
                }
            }
        },
        "/admin/users/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Получить пользователя по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "404": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    },
                    "500": {
                        "description": "Ошибка при получении пользователя",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Обновить данные пользователя",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User update",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "400": {
                        "description": "Некорректное тело запроса",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    },
                    "404": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    },
                    "500": {
                        "description": "Ошибка при обновлении пользователя",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "tags": [
                    "users"
                ],
                "summary": "Удалить пользователя",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    },
                    "500": {
                        "description": "Ошибка при удалении пользователя",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "login payload",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    },
                    "401": {
                        "description": "Неверный email или пароль",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register",
                "parameters": [
                    {
                        "description": "register payload",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "400": {
                        "description": "Некорректные данные",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    },
                    "409": {
                        "description": "Email уже зарегистрирован",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    }
                }
            }
        },
        "/currency": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "currency"
                ],
                "summary": "Получить курсы валют",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.CurrencyRate"
                        }
                    },
                    "500": {
                        "description": "Ошибка получения курсов валют",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    }
                }
            }
        },
        "/news": {
            "get": {
                "description": "Публичный список новостей с фильтрами и пагинацией",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "news"
                ],
                "summary": "List news (public)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Фильтр: hadj|company",
                        "name": "category_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Тип медиа: photo|video",
                        "name": "media_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Поиск по заголовку или excerpt",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Номер страницы (1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Размер страницы (12)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Не удалось получить список новостей",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    }
                }
            }
        },
        "/news/popular": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "news"
                ],
                "summary": "Get popular news",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Количество новостей (по умолчанию 5)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.News"
                            }
                        }
                    },
                    "500": {
                        "description": "Не удалось получить популярные новости",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    }
                }
            }
        },
        "/news/recent": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "news"
                ],
                "summary": "Get recent news",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Количество новостей (по умолчанию 3)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.News"
                            }
                        }
                    },
                    "500": {
                        "description": "Не удалось получить последние новости",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    }
                }
            }
        },
        "/news/{slug_or_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "news"
                ],
                "summary": "Get news by slug or id (public)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slug или ID новости",
                        "name": "slug_or_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.News"
                        }
                    },
                    "404": {
                        "description": "Новость не найдена",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    },
                    "500": {
                        "description": "Не удалось получить новость",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    }
                }
            }
        },
        "/profile": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Получить профиль текущего пользователя",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "401": {
                        "description": "Неавторизованный доступ",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    },
                    "404": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    },
                    "500": {
                        "description": "Ошибка при загрузке профиля",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Обновить профиль текущего пользователя",
                "parameters": [
                    {
                        "description": "Данные профиля",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "400": {
                        "description": "Некорректное тело запроса",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    },
                    "401": {
                        "description": "Неавторизованный доступ",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    },
                    "404": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    },
                    "500": {
                        "description": "Ошибка при обновлении профиля",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    }
                }
            }
        },
        "/trips": {
            "get": {
                "description": "Публичный поиск туров с фильтрацией",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trips"
                ],
                "summary": "List trips",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Город вылета",
                        "name": "departure_city",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Тип тура (пляжный, экскурсионный, семейный)",
                        "name": "trip_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Сезон (например: 2025 или лето 2025)",
                        "name": "season",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Trip"
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка при получении списка туров",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    }
                }
            }
        },
        "/trips/{id}": {
            "get": {
                "description": "Публичный просмотр тура",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trips"
                ],
                "summary": "Get trip by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Trip ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Trip"
                        }
                    },
                    "404": {
                        "description": "Тур не найден",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    },
                    "500": {
                        "description": "Ошибка при получении тура",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    }
                }
            }
        },
        "/trips/{id}/countdown": {
            "get": {
                "description": "Получить обратный отсчёт до конца бронирования",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trips"
                ],
                "summary": "Get booking countdown",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Trip ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "404": {
                        "description": "Тур не найден",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    },
                    "500": {
                        "description": "Ошибка при получении тура",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorData"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "helpers.ErrorData": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "машинный код ошибки",
                    "type": "string"
                },
                "fields": {
                    "description": "ошибки по полям (для валидации)",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "message": {
                    "description": "человеко-читаемый текст (на русском)",
                    "type": "string"
                }
            }
        },
        "models.AuthResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "models.CreateNewsCategoryRequest": {
            "type": "object",
            "properties": {
                "slug": {
                    "type": "string",
                    "example": "hajj_news"
                },
                "title": {
                    "type": "string",
                    "example": "Новости хаджа"
                }
            }
        },
        "models.CreateNewsRequest": {
            "type": "object",
            "properties": {
                "category_id": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "excerpt": {
                    "type": "string"
                },
                "media_type": {
                    "type": "string"
                },
                "preview_url": {
                    "type": "string"
                },
                "published_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "video_url": {
                    "type": "string"
                }
            }
        },
        "models.CreateTripRequest": {
            "type": "object",
            "properties": {
                "booking_deadline": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "departure_city": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "photo_url": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "season": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "trip_type": {
                    "type": "string"
                }
            }
        },
        "models.CreateUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role_id": {
                    "type": "integer"
                }
            }
        },
        "models.KV": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 42
                },
                "key": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "models.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "models.News": {
            "type": "object",
            "properties": {
                "author_id": {
                    "type": "integer"
                },
                "category_id": {
                    "type": "integer"
                },
                "comments_count": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "excerpt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "media_type": {
                    "type": "string"
                },
                "preview_url": {
                    "type": "string"
                },
                "published_at": {
                    "type": "string"
                },
                "reposts_count": {
                    "type": "integer"
                },
                "slug": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "video_url": {
                    "type": "string"
                },
                "views_count": {
                    "type": "integer"
                }
            }
        },
        "models.NewsCategory": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "slug": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "models.Stats": {
            "type": "object",
            "properties": {
                "news_by_category": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.KV"
                    }
                },
                "news_by_status": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.KV"
                    }
                },
                "total_news": {
                    "type": "integer",
                    "example": 25
                },
                "total_trips": {
                    "type": "integer",
                    "example": 12
                },
                "total_users": {
                    "type": "integer",
                    "example": 100
                },
                "trips_by_city": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.KV"
                    }
                },
                "trips_by_type": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.KV"
                    }
                },
                "users_by_role": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.KV"
                    }
                }
            }
        },
        "models.Trip": {
            "type": "object",
            "properties": {
                "booking_deadline": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "departure_city": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "photo_url": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "season": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "trip_type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.UpdateNewsCategoryRequest": {
            "type": "object",
            "properties": {
                "slug": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.UpdateNewsRequest": {
            "type": "object",
            "properties": {
                "category_id": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "excerpt": {
                    "type": "string"
                },
                "media_type": {
                    "type": "string"
                },
                "preview_url": {
                    "type": "string"
                },
                "published_at": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "video_url": {
                    "type": "string"
                }
            }
        },
        "models.UpdateProfileRequest": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                }
            }
        },
        "models.UpdateTripRequest": {
            "type": "object",
            "properties": {
                "booking_deadline": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "departure_city": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "photo_url": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "season": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "trip_type": {
                    "type": "string"
                }
            }
        },
        "models.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "full_name": {
                    "type": "string"
                },
                "role_id": {
                    "type": "integer"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "role_id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "services.CurrencyRate": {
            "type": "object",
            "properties": {
                "sar": {
                    "description": "риал",
                    "type": "number"
                },
                "usd": {
                    "type": "number"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Travel API",
	Description:      "API for Travel project",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
