name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Task
        run: |
          curl -sL https://taskfile.dev/install.sh | sh
          sudo mv ./bin/task /usr/local/bin/task
      - name: Install swag CLI
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Run CI pipeline (lint + test + build)
        run: task ci

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: travel-api
          path: bin/travel-api

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: travel-api
          path: .

      - name: Deploy to production
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          source: "travel-api"
          target: "/home/${{ secrets.PROD_USER }}/travel-backend/bin"

      - name: Restart service + run migrations
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            systemctl restart travel-api
            systemctl status travel-api --no-pager
            /home/${{ secrets.PROD_USER }}/travel-backend/bin/travel-api migrate up
